### ISSUE TITLE
Deprecated link for dataset

### ISSUE THREAD

**Issue by kimyoonduk** [zzzace2000/nodegam#1]
While running the 'bikeshare_node_ga2m.ipynb' notebook file, the bikeshare.zip file does not download properly.
The url 'https://docs.google.com/uc?id=1sHpV9q3_tK0Uov2iRxT6TzTiRZxyx9K8' in the fetch_BIKESHARE() function at lib/data.py seems to be deprecated.
I'm encountering the same issue for other datasets.

**Comment by zzzace2000** [comment]
Thanks for catching it! Yes, I realize my Gdrive was expired last month. I just updated the code to use my Onedrive link. Please update the code, or you can download the dataset yourself here:

https://1drv.ms/u/s!ArHmmFHCSXTIg8dZca1ThGeiPqWUCQ?e=ps8Q6T

**Comment by kimyoonduk** [comment]
Thanks for the quick response! Best of luck on your research.
