### ISSUE TITLE
catboost==0.12.2 version - no longer found in regular pypi repos?

### ISSUE THREAD

**Issue by utke1** [zzzace2000/nodegam#4]
https://github.com/zzzace2000/nodegam/blob/79c8675e65d75237f2e853ae55bbc40ae7124ee9/requirements.txt#L5

I see as the error message: 
```
ERROR: Could not find a version that satisfies the requirement catboost==0.12.2 (from versions: 0.1.1.2, 0.20, 0.20.1, 0.20.2, 0.21, 0.22, 0.23, 0.23.1, 0.23.2, 0.24, 0.24.1, 0.24.2, 0.24.3, 0.24.4, 0.25, 0.25.1, 0.26, 0.26.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6)
ERROR: No matching distribution found for catboost==0.12.2
```
Am I missing something obvious or could you update this requirement?

**Comment by zzzace2000** [comment]
Sure let me test it on colab quickly.

**Comment by zzzace2000** [comment]
Just fixed it. Please download the latest code. I made the fp16 optional and fix the requirements. 

You can test the colab here:
https://colab.research.google.com/drive/1C_gBoSc1AlQ7VvCXVWiU-7X3YjQZTiZI?usp=sharing
